### **Project Title: Space-Time Clustering of Mobility Patterns and Air Quality Hotspots**

Install Required Packages
and import Libraries

In [5]:
!pip install pygeohash
!pip install folium
!pip install uszipcode
!pip install geopandas
!pip install datascience

Requirement already satisfied: pygeohash in /opt/anaconda3/lib/python3.12/site-packages (3.0.1)
Requirement already satisfied: folium in /opt/anaconda3/lib/python3.12/site-packages (0.19.5)
Requirement already satisfied: branca>=0.6.0 in /opt/anaconda3/lib/python3.12/site-packages (from folium) (0.8.1)
Requirement already satisfied: jinja2>=2.9 in /opt/anaconda3/lib/python3.12/site-packages (from folium) (3.1.4)
Requirement already satisfied: numpy in /opt/anaconda3/lib/python3.12/site-packages (from folium) (1.26.4)
Requirement already satisfied: requests in /opt/anaconda3/lib/python3.12/site-packages (from folium) (2.32.3)
Requirement already satisfied: xyzservices in /opt/anaconda3/lib/python3.12/site-packages (from folium) (2022.9.0)
Requirement already satisfied: MarkupSafe>=2.0 in /opt/anaconda3/lib/python3.12/site-packages (from jinja2>=2.9->folium) (2.1.3)
Requirement already satisfied: charset-normalizer<4,>=2 in /opt/anaconda3/lib/python3.12/site-packages (from requests->folium) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in /opt/anaconda3/lib/python3.12/site-packages (from requests->folium) (3.7)
Requirement already satisfied: urllib3<3,>=1.21.1 in /opt/anaconda3/lib/python3.12/site-packages (from requests->folium) (2.2.3)
Requirement already satisfied: certifi>=2017.4.17 in /opt/anaconda3/lib/python3.12/site-packages (from requests->folium) (2025.1.31)
Requirement already satisfied: uszipcode in /opt/anaconda3/lib/python3.12/site-packages (1.0.1)
Requirement already satisfied: attrs in /opt/anaconda3/lib/python3.12/site-packages (from uszipcode) (23.1.0)
Requirement already satisfied: requests in /opt/anaconda3/lib/python3.12/site-packages (from uszipcode) (2.32.3)
Requirement already satisfied: pathlib-mate in /opt/anaconda3/lib/python3.12/site-packages (from uszipcode) (1.3.2)
Requirement already satisfied: atomicwrites in /opt/anaconda3/lib/python3.12/site-packages (from uszipcode) (1.4.0)
Requirement already satisfied: fuzzywuzzy in /opt/anaconda3/lib/python3.12/site-packages (from uszipcode) (0.18.0)
Requirement already satisfied: haversine>=2.5.0 in /opt/anaconda3/lib/python3.12/site-packages (from uszipcode) (2.9.0)
Requirement already satisfied: SQLAlchemy>=1.4.0 in /opt/anaconda3/lib/python3.12/site-packages (from uszipcode) (2.0.34)
Requirement already satisfied: sqlalchemy-mate>=1.4.28.3 in /opt/anaconda3/lib/python3.12/site-packages (from uszipcode) (2.0.0.3)
Requirement already satisfied: typing-extensions>=4.6.0 in /opt/anaconda3/lib/python3.12/site-packages (from SQLAlchemy>=1.4.0->uszipcode) (4.11.0)
Requirement already satisfied: greenlet!=0.4.17 in /opt/anaconda3/lib/python3.12/site-packages (from SQLAlchemy>=1.4.0->uszipcode) (3.0.1)
Requirement already satisfied: prettytable<4.0.0,>=3.0.0 in /opt/anaconda3/lib/python3.12/site-packages (from sqlalchemy-mate>=1.4.28.3->uszipcode) (3.16.0)
Requirement already satisfied: charset-normalizer<4,>=2 in /opt/anaconda3/lib/python3.12/site-packages (from requests->uszipcode) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in /opt/anaconda3/lib/python3.12/site-packages (from requests->uszipcode) (3.7)
Requirement already satisfied: urllib3<3,>=1.21.1 in /opt/anaconda3/lib/python3.12/site-packages (from requests->uszipcode) (2.2.3)
Requirement already satisfied: certifi>=2017.4.17 in /opt/anaconda3/lib/python3.12/site-packages (from requests->uszipcode) (2025.1.31)
Requirement already satisfied: wcwidth in /opt/anaconda3/lib/python3.12/site-packages (from prettytable<4.0.0,>=3.0.0->sqlalchemy-mate>=1.4.28.3->uszipcode) (0.2.5)
Requirement already satisfied: geopandas in /opt/anaconda3/lib/python3.12/site-packages (1.0.1)
Requirement already satisfied: numpy>=1.22 in /opt/anaconda3/lib/python3.12/site-packages (from geopandas) (1.26.4)
Requirement already satisfied: pyogrio>=0.7.2 in /opt/anaconda3/lib/python3.12/site-packages (from geopandas) (0.10.0)
Requirement already satisfied: packaging in /opt/anaconda3/lib/python3.12/site-packages (from geopandas) (24.1)
Requirement already satisfied: pandas>=1.4.0 in /opt/anaconda3/lib/python3.12/site-packages (from geopandas) (2.2.2)
Requirement already satisfied: pyproj>=3.3.0 in /opt/anaconda3/lib/python3.12/site-packages (from geopandas) (3.6.1)
Requirement already satisfied: shapely>=2.0.0 in /opt/anaconda3/lib/python3.12/site-packages (from geopandas) (2.0.5)
Requirement already satisfied: python-dateutil>=2.8.2 in /opt/anaconda3/lib/python3.12/site-packages (from pandas>=1.4.0->geopandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /opt/anaconda3/lib/python3.12/site-packages (from pandas>=1.4.0->geopandas) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in /opt/anaconda3/lib/python3.12/site-packages (from pandas>=1.4.0->geopandas) (2023.3)
Requirement already satisfied: certifi in /opt/anaconda3/lib/python3.12/site-packages (from pyogrio>=0.7.2->geopandas) (2025.1.31)
Requirement already satisfied: six>=1.5 in /opt/anaconda3/lib/python3.12/site-packages (from python-dateutil>=2.8.2->pandas>=1.4.0->geopandas) (1.16.0)
Collecting datascience
  Downloading datascience-0.17.6-py3-none-any.whl.metadata (688 bytes)
Requirement already satisfied: folium>=0.9.1 in /opt/anaconda3/lib/python3.12/site-packages (from datascience) (0.19.5)
Requirement already satisfied: setuptools in /opt/anaconda3/lib/python3.12/site-packages (from datascience) (75.1.0)
Requirement already satisfied: matplotlib>=3.0.0 in /opt/anaconda3/lib/python3.12/site-packages (from datascience) (3.9.2)
Requirement already satisfied: pandas in /opt/anaconda3/lib/python3.12/site-packages (from datascience) (2.2.2)
Requirement already satisfied: scipy in /opt/anaconda3/lib/python3.12/site-packages (from datascience) (1.13.1)
Requirement already satisfied: numpy in /opt/anaconda3/lib/python3.12/site-packages (from datascience) (1.26.4)
Requirement already satisfied: ipython in /opt/anaconda3/lib/python3.12/site-packages (from datascience) (8.27.0)
Requirement already satisfied: plotly in /opt/anaconda3/lib/python3.12/site-packages (from datascience) (5.24.1)
Requirement already satisfied: branca in /opt/anaconda3/lib/python3.12/site-packages (from datascience) (0.8.1)
Requirement already satisfied: jinja2>=2.9 in /opt/anaconda3/lib/python3.12/site-packages (from folium>=0.9.1->datascience) (3.1.4)
Requirement already satisfied: requests in /opt/anaconda3/lib/python3.12/site-packages (from folium>=0.9.1->datascience) (2.32.3)
Requirement already satisfied: xyzservices in /opt/anaconda3/lib/python3.12/site-packages (from folium>=0.9.1->datascience) (2022.9.0)
Requirement already satisfied: contourpy>=1.0.1 in /opt/anaconda3/lib/python3.12/site-packages (from matplotlib>=3.0.0->datascience) (1.2.0)
Requirement already satisfied: cycler>=0.10 in /opt/anaconda3/lib/python3.12/site-packages (from matplotlib>=3.0.0->datascience) (0.11.0)
Requirement already satisfied: fonttools>=4.22.0 in /opt/anaconda3/lib/python3.12/site-packages (from matplotlib>=3.0.0->datascience) (4.51.0)
Requirement already satisfied: kiwisolver>=1.3.1 in /opt/anaconda3/lib/python3.12/site-packages (from matplotlib>=3.0.0->datascience) (1.4.4)
Requirement already satisfied: packaging>=20.0 in /opt/anaconda3/lib/python3.12/site-packages (from matplotlib>=3.0.0->datascience) (24.1)
Requirement already satisfied: pillow>=8 in /opt/anaconda3/lib/python3.12/site-packages (from matplotlib>=3.0.0->datascience) (10.4.0)
Requirement already satisfied: pyparsing>=2.3.1 in /opt/anaconda3/lib/python3.12/site-packages (from matplotlib>=3.0.0->datascience) (3.1.2)
Requirement already satisfied: python-dateutil>=2.7 in /opt/anaconda3/lib/python3.12/site-packages (from matplotlib>=3.0.0->datascience) (2.9.0.post0)
Requirement already satisfied: decorator in /opt/anaconda3/lib/python3.12/site-packages (from ipython->datascience) (5.1.1)
Requirement already satisfied: jedi>=0.16 in /opt/anaconda3/lib/python3.12/site-packages (from ipython->datascience) (0.19.1)
Requirement already satisfied: matplotlib-inline in /opt/anaconda3/lib/python3.12/site-packages (from ipython->datascience) (0.1.6)
Requirement already satisfied: prompt-toolkit<3.1.0,>=3.0.41 in /opt/anaconda3/lib/python3.12/site-packages (from ipython->datascience) (3.0.43)
Requirement already satisfied: pygments>=2.4.0 in /opt/anaconda3/lib/python3.12/site-packages (from ipython->datascience) (2.15.1)
Requirement already satisfied: stack-data in /opt/anaconda3/lib/python3.12/site-packages (from ipython->datascience) (0.2.0)
Requirement already satisfied: traitlets>=5.13.0 in /opt/anaconda3/lib/python3.12/site-packages (from ipython->datascience) (5.14.3)
Requirement already satisfied: pexpect>4.3 in /opt/anaconda3/lib/python3.12/site-packages (from ipython->datascience) (4.8.0)
Requirement already satisfied: pytz>=2020.1 in /opt/anaconda3/lib/python3.12/site-packages (from pandas->datascience) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in /opt/anaconda3/lib/python3.12/site-packages (from pandas->datascience) (2023.3)
Requirement already satisfied: tenacity>=6.2.0 in /opt/anaconda3/lib/python3.12/site-packages (from plotly->datascience) (8.2.3)
Requirement already satisfied: parso<0.9.0,>=0.8.3 in /opt/anaconda3/lib/python3.12/site-packages (from jedi>=0.16->ipython->datascience) (0.8.3)
Requirement already satisfied: MarkupSafe>=2.0 in /opt/anaconda3/lib/python3.12/site-packages (from jinja2>=2.9->folium>=0.9.1->datascience) (2.1.3)
Requirement already satisfied: ptyprocess>=0.5 in /opt/anaconda3/lib/python3.12/site-packages (from pexpect>4.3->ipython->datascience) (0.7.0)
Requirement already satisfied: wcwidth in /opt/anaconda3/lib/python3.12/site-packages (from prompt-toolkit<3.1.0,>=3.0.41->ipython->datascience) (0.2.5)
Requirement already satisfied: six>=1.5 in /opt/anaconda3/lib/python3.12/site-packages (from python-dateutil>=2.7->matplotlib>=3.0.0->datascience) (1.16.0)
Requirement already satisfied: charset-normalizer<4,>=2 in /opt/anaconda3/lib/python3.12/site-packages (from requests->folium>=0.9.1->datascience) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in /opt/anaconda3/lib/python3.12/site-packages (from requests->folium>=0.9.1->datascience) (3.7)
Requirement already satisfied: urllib3<3,>=1.21.1 in /opt/anaconda3/lib/python3.12/site-packages (from requests->folium>=0.9.1->datascience) (2.2.3)
Requirement already satisfied: certifi>=2017.4.17 in /opt/anaconda3/lib/python3.12/site-packages (from requests->folium>=0.9.1->datascience) (2025.1.31)
Requirement already satisfied: executing in /opt/anaconda3/lib/python3.12/site-packages (from stack-data->ipython->datascience) (0.8.3)
Requirement already satisfied: asttokens in /opt/anaconda3/lib/python3.12/site-packages (from stack-data->ipython->datascience) (2.0.5)
Requirement already satisfied: pure-eval in /opt/anaconda3/lib/python3.12/site-packages (from stack-data->ipython->datascience) (0.2.2)
Downloading datascience-0.17.6-py3-none-any.whl (732 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 732.8/732.8 kB 1.2 MB/s eta 0:00:00a 0:00:01
Installing collected packages: datascience
Successfully installed datascience-0.17.6

In [ ]:
from datascience import *
import pandas as pd
import geopandas as gpd
import pygeohash as gh
import numpy as np
from shapely.geometry import Polygon
from shapely.geometry import Point
from geopandas.tools import sjoin
import matplotlib.pyplot as plt

plt.style.use('fivethirtyeight')

## **1. Data Exploration & Cleaning**

Steps:
Inspect each dataset:

*   Check dtypes format , timestamp formats, intial statistics, spatial coordinates, and column consistency.

*   Remove erroneous coordinates like (0,0).

*   Convert timestamps to a consistent format.

*   Clean and handle missing/null values.

Read CSV files NYC_AQ, NYC_pm,nyc1 and gejson file nyc_polygon

In [115]:
#Read the CSV file containing PM sensors readings and AQ file
PM_data = pd.read_csv('https://raw.githubusercontent.com/Dr-Isam-ALJAWARNEH/fds-project-space-time-clustering-for-aq/refs/heads/main/Datasets/NYC_PM.csv',index_col=False)
AQ_data = pd.read_csv('https://raw.githubusercontent.com/Dr-Isam-ALJAWARNEH/fds-project-space-time-clustering-for-aq/refs/heads/main/Datasets/NYC_AQ.csv',index_col=False)
nyc1_data = pd.read_csv('nyc1.csv')
#Read the GeoJSON file containing neighborhood boundaries into a GeoDataFrame
nyc_neighborhoods = gpd.read_file('https://raw.githubusercontent.com/Dr-Isam-ALJAWARNEH/fds-project-space-time-clustering-for-aq/refs/heads/main/Datasets/nyc_polygon.geojson')

In [116]:
print("AQ_data",AQ_data.shape)
print("PM_data",PM_data.shape)
print("nyc1_data",nyc1_data.shape)
print("nyc_neighborhoods",nyc_neighborhoods.shape)

print("----------------------AQ_data-----------------------")
print(AQ_data.describe())
print(AQ_data.info())
print("----------------------PM_data-----------------------")
print(PM_data.describe())
print(PM_data.info())
print("----------------------nyc1_data-----------------------")
print(nyc1_data.describe())
print(nyc1_data.info())

AQ_data (169999, 31)
PM_data (118765, 33)
nyc1_data (1445285, 22)
nyc_neighborhoods (310, 5)
----------------------AQ_data-----------------------
               time       latitude      longitude           bin0  \
count  1.699990e+05  169999.000000  169999.000000  169999.000000
mean   1.634506e+09      40.826202     -73.892555      78.485926
std    2.197971e+06       0.017215       0.019362     148.612154
min    1.631277e+09      40.711689     -73.934052       0.000000
25%    1.632808e+09      40.813564     -73.911232      16.000000
50%    1.633554e+09      40.818981     -73.892303      39.000000
75%    1.636266e+09      40.845383     -73.870804      92.000000
max    1.639579e+09      40.904430     -73.820808    6233.000000

                bin1           bin2           bin3           bin4  \
count  169999.000000  169999.000000  169999.000000  169999.000000
mean        8.056747       1.885382       0.551209       0.806628
std        22.639578       4.616222       1.461197       1.969984
min         0.000000       0.000000       0.000000       0.000000
25%         1.000000       0.000000       0.000000       0.000000
50%         3.000000       1.000000       0.000000       0.000000
75%         9.000000       2.000000       1.000000       1.000000
max      2493.000000     305.000000     106.000000     101.000000

                bin5           bin6  ...          bin17          bin18  \
count  169999.000000  169999.000000  ...  169999.000000  169999.000000
mean        0.578003       0.367173  ...       0.000247       0.000159
std         1.535912       1.020670  ...       0.016086       0.012602
min         0.000000       0.000000  ...       0.000000       0.000000
25%         0.000000       0.000000  ...       0.000000       0.000000
50%         0.000000       0.000000  ...       0.000000       0.000000
75%         1.000000       0.000000  ...       0.000000       0.000000
max        92.000000      59.000000  ...       2.000000       1.000000

               bin19          bin20          bin21          bin22  \
count  169999.000000  169999.000000  169999.000000  169999.000000
mean        0.000118       0.000059       0.000065       0.000047
std         0.010846       0.007669       0.008044       0.006860
min         0.000000       0.000000       0.000000       0.000000
25%         0.000000       0.000000       0.000000       0.000000
50%         0.000000       0.000000       0.000000       0.000000
75%         0.000000       0.000000       0.000000       0.000000
max         1.000000       1.000000       1.000000       1.000000

               bin23    temperature       humidity           pm25
count  169999.000000  169999.000000  169999.000000  169999.000000
mean        0.000141      17.432182      56.241018       4.310939
std         0.012366       6.659859      16.583384       1.794719
min         0.000000     -37.000000       0.000000       1.568473
25%         0.000000      12.400000      42.200000       3.162405
50%         0.000000      18.400000      55.300000       4.251249
75%         0.000000      22.600000      69.000000       4.786389
max         2.000000      32.400000     100.000000      12.744419

[8 rows x 30 columns]
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 169999 entries, 0 to 169998
Data columns (total 31 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   SensorID     169999 non-null  object
 1   time         169999 non-null  int64
 2   latitude     169999 non-null  float64
 3   longitude    169999 non-null  float64
 4   bin0         169999 non-null  int64
 5   bin1         169999 non-null  int64
 6   bin2         169999 non-null  int64
 7   bin3         169999 non-null  int64
 8   bin4         169999 non-null  int64
 9   bin5         169999 non-null  int64
 10  bin6         169999 non-null  int64
 11  bin7         169999 non-null  int64
 12  bin8         169999 non-null  int64
 13  bin9         169999 non-null  int64
 14  bin10        169999 non-null  int64
 15  bin11        169999 non-null  int64
 16  bin12        169999 non-null  int64
 17  bin13        169999 non-null  int64
 18  bin14        169999 non-null  int64
 19  bin15        169999 non-null  int64
 20  bin16        169999 non-null  int64
 21  bin17        169999 non-null  int64
 22  bin18        169999 non-null  int64
 23  bin19        169999 non-null  int64
 24  bin20        169999 non-null  int64
 25  bin21        169999 non-null  int64
 26  bin22        169999 non-null  int64
 27  bin23        169999 non-null  int64
 28  temperature  169999 non-null  float64
 29  humidity     169999 non-null  float64
 30  pm25         169999 non-null  float64
dtypes: float64(5), int64(25), object(1)
memory usage: 40.2+ MB
None
----------------------PM_data-----------------------
               time       latitude      longitude           bin0  \
count  1.187650e+05  118765.000000  118765.000000  118765.000000
mean   1.580374e+09      40.825551     -73.891823      44.660321
std    5.347413e+05       0.029206       0.025815     151.277083
min    1.579562e+09      40.008129     -74.009636       0.000000
25%    1.579806e+09      40.815228     -73.898399       9.000000
50%    1.580330e+09      40.821003     -73.890045      21.000000
75%    1.580824e+09      40.846992     -73.872032      57.000000
max    1.581927e+09      40.913586     -73.795425   18441.000000

                bin1           bin2           bin3           bin4  \
count  118765.000000  118765.000000  118765.000000  118765.000000
mean        8.255429       2.926519       1.033183       0.985930
std        77.556461      72.625702      71.675580      71.659975
min         0.000000       0.000000       0.000000       0.000000
25%         1.000000       0.000000       0.000000       0.000000
50%         3.000000       1.000000       0.000000       0.000000
75%         7.000000       2.000000       1.000000       1.000000
max     12336.000000   12336.000000   12336.000000   12336.000000

                bin5           bin6  ...          bin19          bin20  \
count  118765.000000  118765.000000  ...  118764.000000  118764.000000
mean        0.723698       0.621665  ...       0.415959       0.415865
std        71.601659      71.596868  ...      71.590678      71.590677
min         0.000000       0.000000  ...       0.000000       0.000000
25%         0.000000       0.000000  ...       0.000000       0.000000
50%         0.000000       0.000000  ...       0.000000       0.000000
75%         0.000000       0.000000  ...       0.000000       0.000000
max     12336.000000   12336.000000  ...   12336.000000   12336.000000

               bin21          bin22          bin23    temperature  \
count  118764.000000  118765.000000  118765.000000  118765.000000
mean        0.420036       1.212895       0.416333       8.244883
std        71.606377     314.941845      71.590381      30.873266
min         0.000000  -10483.508000       0.000000      -7.900000
25%         0.000000       0.000000       0.000000       5.000000
50%         0.000000       0.000000       0.000000       7.200000
75%         0.000000       0.000000       0.000000      11.000000
max     12336.000000  105174.000000   12336.000000   10471.000000

            humidity            pm1           pm25           pm10
count  118765.000000  118765.000000  118765.000000  118765.000000
mean       50.159159       3.386134       7.361118      24.230964
std        21.086862       6.510014      20.559545     298.925781
min         0.000000       0.000000       0.000000       0.000000
25%        35.100000       0.720000       0.900000       0.910000
50%        46.300000       1.670000       3.010000       3.200000
75%        64.700000       3.830000       7.700000      12.290000
max       104.200000     213.240000    3267.020000   87341.710000

[8 rows x 32 columns]
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 118765 entries, 0 to 118764
Data columns (total 33 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   SensorID     118765 non-null  object
 1   time         118765 non-null  int64
 2   latitude     118765 non-null  float64
 3   longitude    118765 non-null  float64
 4   bin0         118765 non-null  int64
 5   bin1         118765 non-null  int64
 6   bin2         118765 non-null  int64
 7   bin3         118765 non-null  int64
 8   bin4         118765 non-null  int64
 9   bin5         118765 non-null  int64
 10  bin6         118765 non-null  int64
 11  bin7         118765 non-null  int64
 12  bin8         118765 non-null  int64
 13  bin9         118765 non-null  int64
 14  bin10        118765 non-null  int64
 15  bin11        118765 non-null  int64
 16  bin12        118764 non-null  float64
 17  bin13        118763 non-null  float64
 18  bin14        118764 non-null  float64
 19  bin15        118765 non-null  float64
 20  bin16        118765 non-null  float64
 21  bin17        118765 non-null  float64
 22  bin18        118765 non-null  float64
 23  bin19        118764 non-null  float64
 24  bin20        118764 non-null  float64
 25  bin21        118764 non-null  float64
 26  bin22        118765 non-null  float64
 27  bin23        118765 non-null  float64
 28  temperature  118765 non-null  float64
 29  humidity     118765 non-null  float64
 30  pm1          118765 non-null  float64
 31  pm25         118765 non-null  float64
 32  pm10         118765 non-null  float64
dtypes: float64(19), int64(13), object(1)
memory usage: 29.9+ MB
None
----------------------nyc1_data-----------------------
                 id      VendorID    RateCodeID  Pickup_longitude  \
count  1.445285e+06  1.445285e+06  1.445285e+06      1.445285e+06
mean   7.226420e+05  1.781941e+00  1.097067e+00     -7.381009e+01
std    4.172180e+05  4.129281e-01  6.163103e-01      3.091071e+00
min    0.000000e+00  1.000000e+00  1.000000e+00     -1.151813e+02
25%    3.613210e+05  2.000000e+00  1.000000e+00     -7.396053e+01
50%    7.226420e+05  2.000000e+00  1.000000e+00     -7.394639e+01
75%    1.083963e+06  2.000000e+00  1.000000e+00     -7.391827e+01
max    1.445284e+06  2.000000e+00  9.900000e+01      0.000000e+00

       Pickup_latitude  Dropoff_longitude  Dropoff_latitude  Passenger_count  \
count     1.445285e+06       1.445285e+06      1.445285e+06     1.445285e+06
mean      4.067522e+01      -7.381805e+01      4.067843e+01     1.360637e+00
std       1.697484e+00       2.979353e+00      1.635611e+00     1.029732e+00
min       0.000000e+00      -1.151789e+02      0.000000e+00     0.000000e+00
25%       4.069370e+01      -7.396776e+01      4.069477e+01     1.000000e+00
50%       4.074584e+01      -7.394553e+01      4.074571e+01     1.000000e+00
75%       4.080022e+01      -7.391198e+01      4.078822e+01     1.000000e+00
max       4.316801e+01       0.000000e+00      4.269479e+01     9.000000e+00

       Trip_distance   Fare_amount         Extra       MTA_tax    Tip_amount  \
count   1.445285e+06  1.445285e+06  1.445285e+06  1.445285e+06  1.445285e+06
mean    2.757192e+00  1.194466e+01  3.475314e-01  4.860920e-01  1.248817e+00
std     2.953487e+00  1.051256e+01  3.740171e-01  8.824990e-02  2.777279e+00
min     0.000000e+00 -4.928000e+02 -1.000000e+00 -5.000000e-01 -6.700000e+00
25%     1.000000e+00  6.000000e+00  0.000000e+00  5.000000e-01  0.000000e+00
50%     1.800000e+00  9.000000e+00  5.000000e-01  5.000000e-01  0.000000e+00
75%     3.450000e+00  1.450000e+01  5.000000e-01  5.000000e-01  2.000000e+00
max     3.605000e+02  9.890000e+02  8.300000e+01  3.000000e+00  4.000000e+02

       Tolls_amount  Ehail_fee  improvement_surcharge  Total_amount  \
count  1.445285e+06        0.0           1.445285e+06  1.445285e+06
mean   9.968433e-02        NaN           2.916495e-01  1.441838e+01
std    1.183991e+00        NaN           5.269119e-02  1.201146e+01
min   -3.000000e+01        NaN          -3.000000e-01 -4.975000e+02
25%    0.000000e+00        NaN           3.000000e-01  7.800000e+00
50%    0.000000e+00        NaN           3.000000e-01  1.116000e+01
75%    0.000000e+00        NaN           3.000000e-01  1.730000e+01
max    9.000000e+02        NaN           1.390000e+00  1.000800e+03

       Payment_type     Trip_type
count  1.445285e+06  1.445283e+06
mean   1.517152e+00  1.022774e+00
std    5.267786e-01  1.491826e-01
min    1.000000e+00  1.000000e+00
25%    1.000000e+00  1.000000e+00
50%    2.000000e+00  1.000000e+00
75%    2.000000e+00  1.000000e+00
max    5.000000e+00  2.000000e+00
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1445285 entries, 0 to 1445284
Data columns (total 22 columns):
 #   Column                 Non-Null Count    Dtype
---  ------                 --------------    -----
 0   id                     1445285 non-null  int64
 1   VendorID               1445285 non-null  int64
 2   lpep_pickup_datetime   1445285 non-null  object
 3   Lpep_dropoff_datetime  1445285 non-null  object
 4   Store_and_fwd_flag     1445285 non-null  object
 5   RateCodeID             1445285 non-null  int64
 6   Pickup_longitude       1445285 non-null  float64
 7   Pickup_latitude        1445285 non-null  float64
 8   Dropoff_longitude      1445285 non-null  float64
 9   Dropoff_latitude       1445285 non-null  float64
 10  Passenger_count        1445285 non-null  int64
 11  Trip_distance          1445285 non-null  float64
 12  Fare_amount            1445285 non-null  float64
 13  Extra                  1445285 non-null  float64
 14  MTA_tax                1445285 non-null  float64
 15  Tip_amount             1445285 non-null  float64
 16  Tolls_amount           1445285 non-null  float64
 17  Ehail_fee              0 non-null        float64
 18  improvement_surcharge  1445285 non-null  float64
 19  Total_amount           1445285 non-null  float64
 20  Payment_type           1445285 non-null  int64
 21  Trip_type              1445283 non-null  float64
dtypes: float64(14), int64(5), object(3)
memory usage: 242.6+ MB
None

In [197]:
#removing unnecessary data

#######AQ_data######
bin_list=['bin0','bin1','bin2','bin3','bin4','bin5','bin6','bin7','bin8','bin9','bin10','bin11','bin12','bin13','bin14','bin15','bin16','bin17','bin18','bin19','bin20','bin21','bin22','bin23']
for i in bin_list:
    if i in AQ_data.columns:
       AQ_data = AQ_data.drop(columns=[i])
        
#######PM_data######
for i in bin_list:
    if i in PM_data.columns:
       PM_data = PM_data.drop(columns=[i])
list_pm=['pm1','pm10']
for i in list_pm:
    if i in PM_data.columns:
        PM_data = PM_data.drop(columns=[i])
        
#######nyc1_data######
list_nyc1=['Store_and_fwd_flag','RateCodeID','Passenger_count','Fare_amount','MTA_tax','Tip_amount','Extra','Tolls_amount','Ehail_fee','improvement_surcharge','Total_amount','Payment_type']
for i in list_nyc1:
    if i in nyc1_data.columns:
        nyc1_data = nyc1_data.drop(columns=[i])

#remove erroneous coordinates (0,0)
#Convert the Unix epoch time column to datetime and set it as a new column

#######AQ_data######
AQ_data = \
AQ_data[(AQ_data ['latitude']!=0) & \
       (AQ_data ['longitude'] !=0)]
AQ_data ['datetime'] = pd.to_datetime(AQ_data['time'],unit='s')

print("AQ_data",AQ_data.shape)

#######PM_data######
PM_data = \
PM_data[(PM_data ['latitude']!=0) & \
       (PM_data ['longitude'] !=0)]
PM_data ['datetime'] = pd.to_datetime(PM_data['time'],unit='s')

print("PM_data",PM_data.shape)

#######nyc1_data######
nyc1_data = \
nyc1_data[(nyc1_data ['Pickup_longitude']!=0) & \
       (nyc1_data ['Pickup_latitude'] !=0)]
nyc1_data = \
nyc1_data[(nyc1_data ['Dropoff_longitude']!=0) & \
       (nyc1_data ['Dropoff_latitude'] !=0)]

nyc1_data['lpep_pickup_datetime'] = pd.to_datetime(nyc1_data['lpep_pickup_datetime'])
nyc1_data['Lpep_dropoff_datetime'] = pd.to_datetime(nyc1_data['Lpep_dropoff_datetime'])

print("nyc1_data",nyc1_data.shape)

AQ_data (169999, 10)
PM_data (118765, 10)
nyc1_data (1441239, 14)

In [199]:
print("AQ_data time range:")
print("Oldest:", AQ_data['datetime'].min())
print("Newest:", AQ_data['datetime'].max())
AQ_data.head(5)

AQ_data time range:
Oldest: 2021-09-10 12:29:09
Newest: 2021-12-15 14:35:55

,SensorID,time,latitude,longitude,temperature,humidity,pm25,datetime,geohash,time_bin
0,NYCP2_CS01A,1631277304,40.847672,-73.869316,23.7,57.3,4.508813,2021-09-10 12:35:04,dr72rh,2021-09-10 12:20:00
1,NYCP2_CS01A,1631277308,40.847668,-73.869316,23.7,57.8,5.462420,2021-09-10 12:35:08,dr72rh,2021-09-10 12:20:00
2,NYCP2_CS01A,1631277313,40.847649,-73.869362,23.7,57.8,5.154881,2021-09-10 12:35:13,dr72rh,2021-09-10 12:20:00
3,NYCP2_CS01A,1631277318,40.847649,-73.869362,23.6,57.6,4.508813,2021-09-10 12:35:18,dr72rh,2021-09-10 12:20:00
4,NYCP2_CS01A,1631277323,40.847649,-73.869362,23.6,57.5,5.539503,2021-09-10 12:35:23,dr72rh,2021-09-10 12:20:00

In [201]:
print("PM_data time range:")
print("Oldest:", PM_data['datetime'].min())
print("Newest:", PM_data['datetime'].max())
PM_data.head(5)

PM_data time range:
Oldest: 2020-01-20 23:11:00
Newest: 2020-02-17 08:10:00

,SensorID,time,latitude,longitude,temperature,humidity,pm25,datetime,geohash,time_bin
0,NYCP1_01A,1579618560,40.847183,-73.870087,16.3,15.2,5.91,2020-01-21 14:56:00,dr72rh,2020-01-21 14:40:00
1,NYCP1_01A,1579618560,40.847183,-73.870094,16.2,15.1,1.18,2020-01-21 14:56:00,dr72rh,2020-01-21 14:40:00
2,NYCP1_01A,1579618560,40.847179,-73.870094,16.1,15.1,0.76,2020-01-21 14:56:00,dr72rh,2020-01-21 14:40:00
3,NYCP1_01A,1579618560,40.847179,-73.870094,16.1,15.2,4.48,2020-01-21 14:56:00,dr72rh,2020-01-21 14:40:00
4,NYCP1_01A,1579618560,40.847179,-73.870094,16.0,15.2,5.77,2020-01-21 14:56:00,dr72rh,2020-01-21 14:40:00

In [203]:
print("nyc1_data time range:")
print("Oldest pickup_datetime:", nyc1_data['lpep_pickup_datetime'].min())
print("Newest pickup_datetime:", nyc1_data['lpep_pickup_datetime'].max())
print("Oldest dropoff_datetime:", nyc1_data['Lpep_dropoff_datetime'].min())
print("Newest dropoff_datetime:", nyc1_data['Lpep_dropoff_datetime'].max())
nyc1_data.head(5)

nyc1_data time range:
Oldest pickup_datetime: 2016-01-01 00:00:00
Newest pickup_datetime: 2016-01-31 23:59:58
Oldest dropoff_datetime: 2016-01-01 00:00:00
Newest dropoff_datetime: 2016-02-01 23:17:17

,id,VendorID,lpep_pickup_datetime,Lpep_dropoff_datetime,Pickup_longitude,Pickup_latitude,Dropoff_longitude,Dropoff_latitude,Trip_distance,Trip_type,Pickup_geohash,Dropoff_geohash,Pickup_time_bin,Dropoff_time_bin
0,0,2,2016-01-01 00:29:24,2016-01-01 00:39:36,-73.928642,40.680611,-73.924278,40.698044,1.46,1.0,dr5rmt,dr5rtb,2016-01-01 00:20:00,2016-01-01 00:20:00
1,1,2,2016-01-01 00:19:39,2016-01-01 00:39:18,-73.952675,40.723175,-73.923920,40.761379,3.56,1.0,dr5rtj,dr5rvu,2016-01-01 00:00:00,2016-01-01 00:20:00
2,2,2,2016-01-01 00:19:33,2016-01-01 00:39:48,-73.971611,40.676105,-74.013161,40.646072,3.79,1.0,dr5rks,dr5r5z,2016-01-01 00:00:00,2016-01-01 00:20:00
3,3,2,2016-01-01 00:22:12,2016-01-01 00:38:32,-73.989502,40.669579,-74.000648,40.689034,3.01,1.0,dr5rk7,dr5rkp,2016-01-01 00:20:00,2016-01-01 00:20:00
4,4,2,2016-01-01 00:24:01,2016-01-01 00:39:22,-73.964729,40.682854,-73.940720,40.663013,2.55,1.0,dr5rky,dr5rm6,2016-01-01 00:20:00,2016-01-01 00:20:00

In [205]:
nyc_neighborhoods.head(5)

,neighborhood,boroughCode,borough,@id,geometry
0,Allerton,2,Bronx,http://nyc.pediacities.com/Resource/Neighborho...,"POLYGON ((-73.849 40.872, -73.846 40.87, -73.8..."
1,Alley Pond Park,4,Queens,http://nyc.pediacities.com/Resource/Neighborho...,"POLYGON ((-73.743 40.739, -73.744 40.739, -73...."
2,Arden Heights,5,Staten Island,http://nyc.pediacities.com/Resource/Neighborho...,"POLYGON ((-74.17 40.561, -74.17 40.561, -74.16..."
3,Arlington,5,Staten Island,http://nyc.pediacities.com/Resource/Neighborho...,"POLYGON ((-74.16 40.641, -74.16 40.641, -74.16..."
4,Arrochar,5,Staten Island,http://nyc.pediacities.com/Resource/Neighborho...,"POLYGON ((-74.061 40.593, -74.061 40.593, -74...."

## **2. Data Integration**

Aggregate all datasets into a common spatial grid and temporal resolution.

Spatial Aggregation:

*    Create geohash cells over NYC.
*    Spatially join GPS/mobility data and AQ data to these grid cells.

Temporal Aggregation:
*    Resample time to a fixed interval.
*    For each grid cell & time slice, calculate:

      *    Mobility: Count of trips, speed, or density.

      *    Air Quality: Mean PM2.5, humidity, and temprature.

🗺 Spatial Grid:

In [209]:
#Set configuration
geohash_precision= 6

In [211]:
#Generate Geohash for each tuple (long,lat)
AQ_data['geohash']=AQ_data.apply(lambda x: gh.encode(x.latitude,x.longitude,precision=geohash_precision),axis=1)
PM_data['geohash']=PM_data.apply(lambda x: gh.encode(x.latitude,x.longitude,precision=geohash_precision),axis=1)

In [212]:
# generate geohashes for pickup and dropoff points for nyc1.csv file

nyc1_data['Pickup_geohash'] = nyc1_data.apply(lambda x: gh.encode(x['Pickup_latitude'], x['Pickup_longitude'], precision=geohash_precision), axis=1)
nyc1_data['Dropoff_geohash'] = nyc1_data.apply(lambda x: gh.encode(x['Dropoff_latitude'], x['Dropoff_longitude'], precision=geohash_precision), axis=1)

⏱ Temporal Resolution:
* Round timestamps to 20min for alignment. ( we need to explain why we chhose this binning intervals)

🧮 Aggregation:
For each spatial cell (geohash) and time interval (20min):
* Count number of trips, using the total pickup and dropoff points for each (geohash, time_bin).
* Calculate mean PM2.5 , humidity, and temperature.

In [214]:
#######AQ_data#######
# Round the datetime to 20-minute intervals
AQ_data['time_bin'] = AQ_data['datetime'].dt.floor('20min')

# Group by geohash and the time_bin column
AQ_aggregated = AQ_data.groupby(['geohash', 'time_bin']).agg({
    'temperature': 'mean',
    'humidity': 'mean',
    'pm25': 'mean',
    # Add any other columns if you'd like to aggregate
}).reset_index()
print("AQ_aggregated",AQ_aggregated.shape)
AQ_aggregated.head(5)

AQ_aggregated (4585, 5)

  geohash            time_bin  temperature   humidity       pm25
0  dr5rte 2021-10-29 14:40:00    13.700000  64.000000   3.187280
1  dr5ry2 2021-10-29 13:40:00    14.000000  59.300000   3.084182
2  dr5rz9 2021-09-22 14:20:00    29.600000  60.824242  11.387078
3  dr5rz9 2021-09-22 15:00:00    29.501471  64.905147  11.063003
4  dr5rz9 2021-09-22 15:20:00    28.208036  69.866071   9.865907

In [215]:
#######PM_data#######
# Round the datetime to 20-minute intervals
PM_data ['time_bin'] = PM_data ['datetime'].dt.floor('20min')

# Group by geohash and the time_bin column
PM_aggregated = PM_data.groupby(['geohash', 'time_bin']).agg({
    'temperature': 'mean',
    'humidity': 'mean',
    'pm25': 'mean',
    # Add any other columns if you'd like to aggregate
}).reset_index()
print("PM_aggregated",PM_aggregated.shape)
PM_aggregated.head(5)

PM_aggregated (1635, 5)

  geohash            time_bin  temperature   humidity      pm25
0  dr57we 2020-02-05 13:40:00      5.40000  70.600000  0.280000
1  dr57we 2020-02-05 15:40:00      9.30000  46.100000  0.000000
2  dr5ref 2020-02-05 12:20:00      6.30000  68.681818  4.754545
3  dr5reg 2020-02-05 12:20:00      6.30000  69.102410  3.041928
4  dr5reg 2020-02-05 12:40:00      6.18961  69.945022  3.505498

In [226]:
#######nyc1_data#######

# Round the datetime to 20-minute intervals
nyc1_data['Pickup_time_bin'] = nyc1_data['lpep_pickup_datetime'].dt.floor('20min')
nyc1_data['Dropoff_time_bin'] = nyc1_data['Lpep_dropoff_datetime'].dt.floor('20min')

# Group by geohash and the time_bin column
# we will get number of trips (Pickup,Dropoff)points in each geohash during each 20-minute interval.
nyc1_Pickup_points_aggregated = nyc1_data.groupby(['Pickup_geohash', 'Pickup_time_bin']).agg({
    'VendorID': 'count',}).reset_index()
nyc1_Dropoff_points_aggregated = nyc1_data.groupby(['Dropoff_geohash', 'Dropoff_time_bin']).agg({
    'VendorID': 'count',}).reset_index()

In [228]:
print("nyc1_Pickup_points_aggregated",nyc1_Pickup_points_aggregated.shape)
nyc1_Pickup_points_aggregated.head(5)

nyc1_Pickup_points_aggregated (364720, 3)

  Pickup_geohash     Pickup_time_bin  VendorID
0         9qqhg5 2016-01-27 20:40:00         1
1         9qqj6g 2016-01-27 17:20:00         1
2         9qqj74 2016-01-29 01:00:00         1
3         9qqj74 2016-01-29 01:40:00         1
4         9qqj74 2016-01-29 23:00:00         1

In [230]:
print("nyc1_Dropoff_points_aggregated",nyc1_Dropoff_points_aggregated.shape)
nyc1_Dropoff_points_aggregated.head(5)

nyc1_Dropoff_points_aggregated (598410, 3)

  Dropoff_geohash    Dropoff_time_bin  VendorID
0          9qqhg5 2016-01-27 20:20:00         1
1          9qqj74 2016-01-28 21:00:00         1
2          9qqj74 2016-01-29 00:40:00         1
3          9qqj74 2016-01-30 18:20:00         1
4          9qqj74 2016-01-31 23:40:00         1

A clear summary of total mobility activity per (geohash area and 20-minute time bin).

In [242]:
# Rename columns for consistency
nyc1_Pickup_points_aggregated = nyc1_Pickup_points_aggregated.rename(columns={
    'Pickup_geohash': 'geohash',
    'Pickup_time_bin': 'time_bin',
    'VendorID': 'pickup_trip_count'
})

nyc1_Dropoff_points_aggregated = nyc1_Dropoff_points_aggregated.rename(columns={
    'Dropoff_geohash': 'geohash',
    'Dropoff_time_bin': 'time_bin',
    'VendorID': 'dropoff_trip_count'
})

# Merge on geohash and time_bin
nyc1_joined = pd.merge(
    nyc1_Pickup_points_aggregated,
    nyc1_Dropoff_points_aggregated,
    on=['geohash', 'time_bin'],
    how='outer'
)

# Fill missing values with 0
nyc1_joined[['pickup_trip_count', 'dropoff_trip_count']] = nyc1_joined[['pickup_trip_count', 'dropoff_trip_count']].fillna(0).astype(int)

# Add total_trip_count column
nyc1_joined['total_trip_count'] = nyc1_joined['pickup_trip_count'] + nyc1_joined['dropoff_trip_count']


nyc1_joined.head(5) #we need to study the time bin

,geohash,time_bin,pickup_trip_count,dropoff_trip_count,total_trip_count
0,9qqhg5,2016-01-27 20:20:00,0,1,1
1,9qqhg5,2016-01-27 20:40:00,1,0,1
2,9qqj6g,2016-01-27 17:20:00,1,0,1
3,9qqj74,2016-01-28 21:00:00,0,1,1
4,9qqj74,2016-01-29 00:40:00,0,1,1

Note: pd.merge(..., how='outer') — Full Outer Join
🔍 What it does:
Keeps all rows from both tables.

Fills in NaN for missing values where there is no match on the join keys.

🧠 Think of it as:
“Keep everything — even if it only exists in one side.”

Now we will join the three datasets:

nyc1_joined (trip data)
AQ_aggregated (air quality from AQ_data)
PM_aggregated (air quality from PM_data)

by merge them on ['geohash', 'time_bin'].

In [246]:
# Step 1: Merge trip data with AQ data
merged_1 = pd.merge(
    nyc1_joined,
    AQ_aggregated,
    on=['geohash', 'time_bin'],
    how='outer',  # Keep all spatial-temporal combinations
    suffixes=('', '_aq'))

# Step 2: Merge the result with PM data
final_merged = pd.merge(
    merged_1,
    PM_aggregated,
    on=['geohash', 'time_bin'],
    how='outer',
    suffixes=('', '_pm'))

# Step 3: Fill missing counts with 0, and optionally drop/rename columns if needed

final_merged[['pickup_trip_count', 'dropoff_trip_count', 'total_trip_count']] = final_merged[[
    'pickup_trip_count', 'dropoff_trip_count', 'total_trip_count']].fillna(0).astype(int)

# View result
final_merged.head(5)

,geohash,time_bin,pickup_trip_count,dropoff_trip_count,total_trip_count,temperature,humidity,pm25,temperature_pm,humidity_pm,pm25_pm
0,9qqhg5,2016-01-27 20:20:00,0,1,1,NaN,NaN,NaN,NaN,NaN,NaN
1,9qqhg5,2016-01-27 20:40:00,1,0,1,NaN,NaN,NaN,NaN,NaN,NaN
2,9qqj6g,2016-01-27 17:20:00,1,0,1,NaN,NaN,NaN,NaN,NaN,NaN
3,9qqj74,2016-01-28 21:00:00,0,1,1,NaN,NaN,NaN,NaN,NaN,NaN
4,9qqj74,2016-01-29 00:40:00,0,1,1,NaN,NaN,NaN,NaN,NaN,NaN

In [248]:
#find mean for the AQ parameters (temprature, humidity,and pm25)

# Create new columns that store the average of AQ and PM values, handling NaNs safely
final_merged['pm25_mean'] = final_merged[['pm25', 'pm25_pm']].mean(axis=1, skipna=True)
final_merged['humidity_mean'] = final_merged[['humidity', 'humidity_pm']].mean(axis=1, skipna=True)
final_merged['temperature_mean'] = final_merged[['temperature', 'temperature_pm']].mean(axis=1, skipna=True)

final_merged = final_merged.drop(columns=[
    'pm25', 'pm25_pm',
    'humidity', 'humidity_pm',
    'temperature', 'temperature_pm'])

# View result
print(type(final_merged))
final_merged.head()

<class 'pandas.core.frame.DataFrame'>

,geohash,time_bin,pickup_trip_count,dropoff_trip_count,total_trip_count,pm25_mean,humidity_mean,temperature_mean
0,9qqhg5,2016-01-27 20:20:00,0,1,1,NaN,NaN,NaN
1,9qqhg5,2016-01-27 20:40:00,1,0,1,NaN,NaN,NaN
2,9qqj6g,2016-01-27 17:20:00,1,0,1,NaN,NaN,NaN
3,9qqj74,2016-01-28 21:00:00,0,1,1,NaN,NaN,NaN
4,9qqj74,2016-01-29 00:40:00,0,1,1,NaN,NaN,NaN

🗺 Spatial join:
Performing sjoin by taking geohash center point and reflected to the NYC administrative polygons
Using point in polygon spatial join

In [257]:

# Step 1: Decode geohash center to lat/lon
final_merged[['latitude', 'longitude']] = final_merged['geohash'].apply(
    lambda g: pd.Series(gh.decode(g)))

# Step 2: Convert to GeoDataFrame with point geometry
final_merged_gdf = gpd.GeoDataFrame(final_merged,geometry=gpd.points_from_xy(final_merged['longitude'], final_merged['latitude']),
    crs="EPSG:4326" ) 

# Step 3: Ensure both GeoDataFrames are in the same CRS
nyc_neighborhoods = nyc_neighborhoods.to_crs("EPSG:4326")

# Step 4: Spatial join: match each geohash point with its neighborhood polygon
joined = gpd.sjoin(final_merged_gdf, nyc_neighborhoods, how="left", predicate="within")

joined.head(5)

,geohash,time_bin,pickup_trip_count,dropoff_trip_count,total_trip_count,pm25_mean,humidity_mean,temperature_mean,geometry,latitude,longitude,index_right,neighborhood,boroughCode,borough,@id
0,9qqhg5,2016-01-27 20:20:00,0,1,1,NaN,NaN,NaN,POINT (-115.18 36.01),36.010437,-115.175171,NaN,NaN,NaN,NaN,NaN
1,9qqhg5,2016-01-27 20:40:00,1,0,1,NaN,NaN,NaN,POINT (-115.18 36.01),36.010437,-115.175171,NaN,NaN,NaN,NaN,NaN
2,9qqj6g,2016-01-27 17:20:00,1,0,1,NaN,NaN,NaN,POINT (-115.19 36.098),36.098328,-115.186157,NaN,NaN,NaN,NaN,NaN
3,9qqj74,2016-01-28 21:00:00,0,1,1,NaN,NaN,NaN,POINT (-115.18 36.093),36.092834,-115.175171,NaN,NaN,NaN,NaN,NaN
4,9qqj74,2016-01-29 00:40:00,0,1,1,NaN,NaN,NaN,POINT (-115.18 36.093),36.092834,-115.175171,NaN,NaN,NaN,NaN,NaN

🗺 Spatial join:

Useing geohash_to_polygon new defined function to convert each geohash into a bounding box  (polygon).

Performs a polygon-in-polygon spatial join.

In [250]:
#not sure about this satage

# geohash to polygon function
def geohash_to_polygon(gh_str):
    lat, lon = gh.decode(gh_str)
    lat_err, lon_err = gh.decode_exactly(gh_str)[2:]
    lat_min = lat - lat_err
    lat_max = lat + lat_err
    lon_min = lon - lon_err
    lon_max = lon + lon_err
    return Polygon([
        (lon_min, lat_min),
        (lon_max, lat_min),
        (lon_max, lat_max),
        (lon_min, lat_max),
        (lon_min, lat_min)])


# 1. Convert geohash to polygon and then to Geodataframe
final_merged['geometry'] = final_merged['geohash'].apply(geohash_to_polygon)
print(type(final_merged))
gdf = gpd.GeoDataFrame(final_merged, geometry='geometry', crs='EPSG:4326')
print(type(gdf))


# 2. Perform polygon-to-polygon overlay to compute intersections
overlap = gpd.overlay(gdf, nyc_neighborhoods, how='intersection')

# 3. Add area of intersection
overlap['intersect_area'] = overlap.geometry.area

# Area-weighted averaging of trip counts and Uniform (unweighted) averaging of pm25, temperature, and humidity.


# 4. Ensure trip columns are numeric and fill missing with 0
for col in ['pickup_trip_count', 'dropoff_trip_count', 'total_trip_count']:
    overlap[col] = overlap[col].fillna(0)

# 5. Multiply trip counts by intersection area
overlap['weighted_pickup'] = overlap['pickup_trip_count'] * overlap['intersect_area']
overlap['weighted_dropoff'] = overlap['dropoff_trip_count'] * overlap['intersect_area']
overlap['weighted_total'] = overlap['total_trip_count'] * overlap['intersect_area']

# 6. Group by neighborhood AND time_bin
neighborhood_time_summary = overlap.groupby(['neighborhood', 'time_bin']).agg({
    'intersect_area': 'sum',
    'weighted_pickup': 'sum',
    'weighted_dropoff': 'sum',
    'weighted_total': 'sum',
    'pm25_mean': 'mean',            # Uniform average for air quality
    'temperature_mean': 'mean',
    'humidity_mean': 'mean'
}).reset_index()

# 7. Compute area-weighted trip metrics
neighborhood_time_summary['pickup_trip_aw'] = neighborhood_time_summary['weighted_pickup'] / neighborhood_time_summary['intersect_area']
neighborhood_time_summary['dropoff_trip_aw'] = neighborhood_time_summary['weighted_dropoff'] / neighborhood_time_summary['intersect_area']
neighborhood_time_summary['total_trip_aw'] = neighborhood_time_summary['weighted_total'] / neighborhood_time_summary['intersect_area']

# 8. drop intermediate weighted columns
neighborhood_time_summary = neighborhood_time_summary.drop(columns=[
    'weighted_pickup', 'weighted_dropoff', 'weighted_total', 'intersect_area'
])

# Preview the result
print(neighborhood_time_summary.head())




print(largest_only.shape)
print(overlap.shape)

<class 'pandas.core.frame.DataFrame'>
<class 'geopandas.geodataframe.GeoDataFrame'>

/var/folders/h2/2gfk43_97tqgvdv7bgtkdx9r0000gn/T/ipykernel_46291/2605011594.py:30: UserWarning: Geometry is in a geographic CRS. Results from 'area' are likely incorrect. Use 'GeoSeries.to_crs()' to re-project geometries to a projected CRS before this operation.

  overlap['intersect_area'] = overlap.geometry.area

  neighborhood            time_bin  pm25_mean  temperature_mean  \
0     Allerton 2016-01-01 00:00:00        NaN               NaN
1     Allerton 2016-01-01 00:20:00        NaN               NaN
2     Allerton 2016-01-01 00:40:00        NaN               NaN
3     Allerton 2016-01-01 01:00:00        NaN               NaN
4     Allerton 2016-01-01 01:20:00        NaN               NaN

   humidity_mean  pickup_trip_aw  dropoff_trip_aw  total_trip_aw
0            NaN        0.815875         0.403274       1.219148
1            NaN        1.000000         0.000000       1.000000
2            NaN        0.213599         1.527841       1.741440
3            NaN        0.887131         0.885416       1.772547
4            NaN        1.000000         1.434249       2.434249

NameError: name 'largest_only' is not defined